### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by natebeaty** [filipesabella/quick-file-actions#3]
[Enter steps to reproduce below:]
1. Selected delete file from command palette
2. Hit enter to confirm path

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [quick-file-actions](https://github.com/filipesabella/quick-file-actions) package, v0.1.1
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/nate/.atom/packages/quick-file-actions/lib/quick-file-actions-view.js:21

TypeError: undefined is not a function
  at HTMLFormElement.atom.commands.add.core:confirm (/Users/nate/.atom/packages/quick-file-actions/lib/quick-file-actions-view.js:21:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
 17x -1:08.7.0 core:move-down (input.hidden-input)
  4x -1:06.6.0 core:move-up (input.hidden-input)
     -1:05.6.0 core:move-down (input.hidden-input)
     -1:04.4.0 core:move-up (input.hidden-input)
     -1:03.8.0 editor:consolidate-selections (input.hidden-input)
     -1:03.8.0 core:cancel (input.hidden-input)
     -0:24.1.0 settings-view:open (input.hidden-input)
     -0:20.4.0 core:paste (input.hidden-input)
     -0:19.4.0 core:confirm (input.hidden-input)
  3x -0:11.1.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-always.theme-cobalt2-syntax.theme-one-dark-ui)
     -0:08.6.0 command-palette:toggle (input.hidden-input)
     -0:07.7.0 core:backspace (input.hidden-input)
     -0:04.5.0 core:move-down (input.hidden-input)
     -0:03.7.0 core:confirm (input.hidden-input)
     -0:03.7.0 quick-file-actions:delete (input.hidden-input)
     -0:00.5.0 core:confirm (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-alignment"
    ],
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
cobalt2-syntax, v0.2.0
color-picker, v2.0.10
emmet, v2.3.12
minimap, v4.11.2
project-manager, v1.15.11
quick-file-actions, v0.1.1

# Dev
No dev packages
```

**Comment by filipesabella** [comment]
Hey, @natebeaty thanks for reporting the issue.

As you can see, Github didn't notify me of new issues in repositories I own by default, apologies for that.

This issue is quite strange, does it still happen to you? It might've gone away since.. well almost two years of Atom updates.

**Comment by natebeaty** [comment]
No problem — I have no idea, I went back to using Sublime pretty quickly, so I haven't used Atom all that much since reporting this.

**Comment by filipesabella** [comment]
@natebeaty fair enough, thanks for taking the time to reply.
