### ISSUE TITLE
Uncaught TypeError: fsExtra.move is not a function

### ISSUE THREAD

**Issue by tjmehta** [filipesabella/quick-file-actions#6]
[Enter steps to reproduce:]

1) CMD+SHIFT+P
2) "Quick move"
3) Enter new filename or file path

**Atom**: 1.19.0-beta7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [quick-file-actions](https://github.com/filipesabella/quick-file-actions) package 0.2.1

### Stack Trace

Uncaught TypeError: fsExtra.move is not a function

```
At /Applications/AtomLite/.atom/packages/quick-file-actions/lib/file-ops.js:43

TypeError: fsExtra.move is not a function
    at /packages/quick-file-actions/lib/file-ops.js:43:17
    at checkingDestination (/packages/quick-file-actions/lib/file-ops.js:34:7)
    at Object.move (/packages/quick-file-actions/lib/file-ops.js:42:7)
    at move (/packages/quick-file-actions/lib/quick-file-actions.js:45:20)
    at /packages/quick-file-actions/lib/quick-file-actions.js:19:7
    at /packages/quick-file-actions/lib/quick-file-actions-view.js:22:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/AtomLite/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:20.9.0 intentions:highlight (input.hidden-input)
  3x -0:20.8.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:19.8.0 core:backspace (input.hidden-input)
     -0:19.2.0 intentions:highlight (input.hidden-input)
     -0:19.1.0 editor:move-to-end-of-word (input.hidden-input)
     -0:18.7.0 core:move-right (input.hidden-input)
     -0:18.4.0 core:backspace (input.hidden-input)
     -0:17 core:save (input.hidden-input)
     -0:12.8.0 command-palette:toggle (input.hidden-input)
     -0:11.7.0 core:confirm (input.hidden-input)
     -0:11.7.0 quick-file-actions:move (input.hidden-input)
  5x -0:11.2.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:10 core:backspace (input.hidden-input)
  2x -0:09.3.0 editor:move-to-end-of-word (input.hidden-input)
     -0:08.6.0 core:backspace (input.hidden-input)
     -0:08.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-sublime-monokai-syntax 0.4.4 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
Dependents 1.6.6 
fb-phabricator 0.0.0 
flow-ide 1.6.0 
git-blame 1.1.1 
git-plus 7.9.3 
greppage 0.1.0 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
quick-file-actions 0.2.1 
terminal-plus 0.14.5 
tree-view-git-modified 0.7.3 
```

**Comment by filipesabella** [comment]
hey, @tjmehta thanks for the report!

I couldn't reproduce it on my mac on Atom Beta version 1.20.0-beta1, could you please try upgrading it 
and trying again?

**Comment by tjmehta** [comment]
I saw it again yesterday. I will try to get more debug info for you when I see it again.

**Comment by filipesabella** [comment]
@tjmehta ah it doesn't happen always? this is surprising as one would expect a missing method to error out every time.

**Comment by tjmehta** [comment]
Hmm yeah it doesn't happen every time. Will let you know when if I see it
this week
